// @generated by schema-rust-next
#[rustfmt::skip]
use thiserror::Error;
#[rustfmt::skip]
use triad_runtime::{
    AcceptedConnection, AsyncListenerError, AsyncListenerSocket,
    AsyncMultiConnectionRuntime, AsyncMultiListenerDaemon, AsyncMultiListenerDaemonError,
    SocketMode, ArgumentError, ComponentArgument, ComponentCommand, BindingSurface,
    ExitReport, RequestErrorLog,
};
#[rustfmt::skip]
/// The component hook surface for the emitted daemon — the only daemon
/// code the component hand-writes (record 1488 escape hatches).
///
/// The component declares its `Configuration` / `Engine` / `Error` types
/// and `PROCESS_NAME`, and provides the REQUIRED `build_runtime` (the
/// emitter cannot know how to open the component's Store/Engine) plus the
/// typed working-input handler.
pub trait ComponentDaemon: Sized + 'static {
    type Configuration: BindingSurface;
    type ConfigurationError: std::error::Error;
    type Engine: Send + Sync + 'static;
    type Error: std::fmt::Display + Send + Sync + 'static;
    const PROCESS_NAME: &'static str;
    /// Load the binary rkyv `Configuration` from the daemon's single argument.
    fn load_configuration(
        path: &std::path::Path,
    ) -> Result<Self::Configuration, Self::ConfigurationError>;
    /// Open the component's durable Store and construct its Engine.
    fn build_runtime(
        configuration: &Self::Configuration,
    ) -> Result<Self::Engine, Self::Error>;
    /// Lifecycle: called once before the listener serves, once after it stops.
    fn start(engine: &Self::Engine) -> Result<(), Self::Error> {
        let _ = engine;
        Ok(())
    }
    fn stop(engine: &Self::Engine) -> Result<(), Self::Error> {
        let _ = engine;
        Ok(())
    }
    /// Run one accepted working connection. Use this only for a daemon
    /// whose ordinary socket must preserve multiple relation-specific
    /// legacy contracts while the public contracts migrate to schema
    /// roots. The generated daemon owns listener mechanics; the
    /// component owns only relation-specific frame decode/encode.
    fn handle_working_connection(
        engine: &Self::Engine,
        connection: AcceptedConnection,
    ) -> impl std::future::Future<Output = Result<(), Self::Error>> + Send + '_;
    /// Run one accepted meta connection. The meta tier is async task-backed,
    /// but this hook remains the explicit component escape hatch until
    /// the daemon shape names the meta signal contract path.
    fn handle_meta_connection(
        engine: &Self::Engine,
        connection: AcceptedConnection,
    ) -> impl std::future::Future<Output = Result<(), Self::Error>> + Send + '_ {
        async move {
            let _ = engine;
            let _ = connection;
            Ok(())
        }
    }
}
#[rustfmt::skip]
/// argv -> binary `Configuration` -> the bound daemon. The single-argument
/// rule: exactly one argument, a signal-encoded (rkyv) configuration file.
pub struct DaemonCommand<Daemon: ComponentDaemon> {
    command: ComponentCommand,
    daemon: std::marker::PhantomData<fn() -> Daemon>,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonCommand<Daemon> {
    pub fn from_environment() -> Self {
        Self {
            command: ComponentCommand::from_environment(),
            daemon: std::marker::PhantomData,
        }
    }
    pub fn from_arguments<Arguments, Argument>(arguments: Arguments) -> Self
    where
        Arguments: IntoIterator<Item = Argument>,
        Argument: Into<String>,
    {
        Self {
            command: ComponentCommand::from_arguments(arguments),
            daemon: std::marker::PhantomData,
        }
    }
    pub fn configuration(&self) -> Result<Daemon::Configuration, DaemonError<Daemon>> {
        match self.command.signal_file_argument()? {
            ComponentArgument::SignalFile(file) => {
                Daemon::load_configuration(file.as_path())
                    .map_err(DaemonError::Configuration)
            }
            ComponentArgument::InlineNota(_) | ComponentArgument::NotaFile(_) => {
                Err(DaemonError::Argument(ArgumentError::ExpectedSignalFile))
            }
        }
    }
    pub fn run(&self) -> Result<(), DaemonError<Daemon>> {
        tokio::runtime::Runtime::new()
            .map_err(DaemonError::Runtime)?
            .block_on(async {
                Daemon::bind(self.configuration()?)?
                    .run()
                    .await
                    .map_err(DaemonError::from)
            })
    }
}
#[rustfmt::skip]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ListenerTier {
    Working,
    Meta,
}
#[rustfmt::skip]
impl std::fmt::Display for ListenerTier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Working => formatter.write_str("working"),
            Self::Meta => formatter.write_str("meta"),
        }
    }
}
#[rustfmt::skip]
/// The bound daemon constructor on the component trait: builds the engine,
/// wraps it in the generated actor connection runtime, and returns the
/// async task-backed listener shell the `DaemonCommand` drives. The component
/// never writes this by hand — it is emitted as a default method on
/// `ComponentDaemon`.
pub trait DaemonBinder: ComponentDaemon {
    fn bind(
        configuration: Self::Configuration,
    ) -> Result<
        AsyncMultiListenerDaemon<GeneratedDaemonRuntime<Self>>,
        DaemonError<Self>,
    > {
        let engine = Self::build_runtime(&configuration)
            .map_err(DaemonError::Component)?;
        let runtime = GeneratedDaemonRuntime::<Self>::new(engine);
        Ok({
            let working_socket = AsyncListenerSocket::new(
                ListenerTier::Working,
                configuration.socket_path().to_path_buf(),
            );
            let working_socket = match configuration.socket_mode() {
                Some(socket_mode) => working_socket.with_socket_mode(socket_mode),
                None => working_socket,
            };
            let mut listener_sockets = std::vec![working_socket];
            let meta_socket_path = configuration
                .meta_socket_path()
                .ok_or(DaemonError::MissingMetaSocket)?
                .to_path_buf();
            listener_sockets
                .push(
                    AsyncListenerSocket::new(ListenerTier::Meta, meta_socket_path)
                        .with_socket_mode(SocketMode::new(0o600)),
                );
            AsyncMultiListenerDaemon::new(
                    listener_sockets,
                    runtime.clone(),
                    RequestErrorLog::new(Self::PROCESS_NAME),
                )
                .with_concurrency_limit(configuration.request_concurrency_limit())
        })
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonBinder for Daemon {}
#[rustfmt::skip]
/// The generated runtime struct that owns the engine. Its
/// `handle_connection` IS the async decode -> execute -> encode spine.
pub struct GeneratedDaemonRuntime<Daemon: ComponentDaemon> {
    engine: std::sync::Arc<Daemon::Engine>,
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> GeneratedDaemonRuntime<Daemon> {
    fn new(engine: Daemon::Engine) -> Self {
        Self {
            engine: std::sync::Arc::new(engine),
        }
    }
    async fn handle_working_connection(
        &self,
        connection: AcceptedConnection,
    ) -> Result<(), Daemon::Error> {
        Daemon::handle_working_connection(self.engine.as_ref(), connection).await
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> Clone for GeneratedDaemonRuntime<Daemon> {
    fn clone(&self) -> Self {
        Self {
            engine: self.engine.clone(),
        }
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> AsyncMultiConnectionRuntime
for GeneratedDaemonRuntime<Daemon> {
    type Listener = ListenerTier;
    type Error = Daemon::Error;
    async fn start(&self) -> Result<(), Self::Error> {
        Daemon::start(self.engine.as_ref())
    }
    async fn stop(&self) -> Result<(), Self::Error> {
        Daemon::stop(self.engine.as_ref())
    }
    async fn handle_connection(
        &self,
        listener: Self::Listener,
        connection: AcceptedConnection,
    ) -> Result<(), Self::Error> {
        match listener {
            ListenerTier::Working => self.handle_working_connection(connection).await,
            ListenerTier::Meta => {
                Daemon::handle_meta_connection(self.engine.as_ref(), connection).await
            }
        }
    }
}
#[rustfmt::skip]
/// The emitted daemon error: argv, configuration, listener, and the
/// component error. The component's own error rides the `Component` arm.
#[derive(Debug, Error)]
pub enum DaemonError<Daemon: ComponentDaemon> {
    #[error("daemon argument error: {0}")]
    Argument(ArgumentError),
    #[error("daemon configuration error: {0}")]
    Configuration(Daemon::ConfigurationError),
    #[error("daemon runtime error: {0}")]
    Runtime(std::io::Error),
    #[error("daemon listener error: {0}")]
    Listener(AsyncListenerError),
    #[error("daemon meta socket path missing from configuration")]
    MissingMetaSocket,
    #[error("component error: {0}")]
    Component(Daemon::Error),
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> From<ArgumentError> for DaemonError<Daemon> {
    fn from(error: ArgumentError) -> Self {
        Self::Argument(error)
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> From<AsyncMultiListenerDaemonError<Daemon::Error>>
for DaemonError<Daemon> {
    fn from(error: AsyncMultiListenerDaemonError<Daemon::Error>) -> Self {
        match error {
            AsyncMultiListenerDaemonError::Listener(error) => Self::Listener(error),
            AsyncMultiListenerDaemonError::Start(error)
            | AsyncMultiListenerDaemonError::Stop(error) => Self::Component(error),
        }
    }
}
#[rustfmt::skip]
/// The component-agnostic exit body. The component's binary calls
/// `<SpiritDaemon as DaemonEntry>::run_to_exit_code()` from `fn main`.
pub trait DaemonEntry: ComponentDaemon {
    fn run_to_exit_code() -> std::process::ExitCode {
        ExitReport::new(Self::PROCESS_NAME)
            .from_result(DaemonCommand::<Self>::from_environment().run())
    }
}
#[rustfmt::skip]
impl<Daemon: ComponentDaemon> DaemonEntry for Daemon {}
